# Generated by Django 4.0.2 on 2022-02-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_rename_appointments_appointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghour',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='workinghour',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
