# Generated by Django 4.0.2 on 2022-02-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_alter_workinghour_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghour',
            name='day',
            field=models.CharField(choices=[('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='workinghour',
            name='end_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='workinghour',
            name='start_time',
            field=models.TimeField(blank=True),
        ),
    ]
