# Generated by Django 4.0.2 on 2022-02-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_alter_workinghour_day_alter_workinghour_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghour',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workinghour',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
