# Generated by Django 4.0.2 on 2022-02-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_alter_workinghour_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Wating', 'Wating'), ('Approved', 'Approved'), ('Canceled', 'Canceled'), ('Missed', 'Missed'), ('Finished', 'Finished')], max_length=32),
        ),
    ]
