# Generated by Django 4.0.2 on 2022-02-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_alter_appointment_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reschedule',
            field=models.BooleanField(default=False),
        ),
    ]
